apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:
jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: Vuln4ghtest
          artifact-id: f9de4546-4bb2-4ad5-9118-44cf0617aebc
          target-environment: QA 